## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns= ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 157
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1883
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies_df = pd.get_dummies(application_df)
application_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [13]:
# Split our preprocessed data into our features and target arrays
X = application_dummies_df.drop(columns = ['IS_SUCCESSFUL']).values
y = application_dummies_df['IS_SUCCESSFUL'].values


# Split the preprocessed data into a training and testing dataset ==> random_state = 42 for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=16, activation='relu', input_dim=number_input_features)
    )

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=16, activation='relu')
    )

# Output layer
nn.add(
    tf.keras.layers.Dense(units=1, activation='sigmoid')
    )


# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 16)                704

 dense_4 (Dense)             (None, 16)                272

 dense_5 (Dense)             (None, 1)                 17

=================================================================
Total params: 993 (3.88 KB)
Trainable params: 993 (3.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5974 - accuracy: 0.6963
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7266
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5554 - accuracy: 0.7286
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5539 - accuracy: 0.7286
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5522 - accuracy: 0.7302
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5515 - accuracy: 0.7311
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7303
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7305
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7308
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7310
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7322
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7314
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7312
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7318
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7330
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7321
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7341
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7335
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7339
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7341
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7331
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7346
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5445 - accuracy: 0.7336
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7339
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7340
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7334
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7360
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7344
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7341
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7352
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7341
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7352
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7334
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7345
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7338
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7350
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7357
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7353
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7362
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7365
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7356
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7354
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7359
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7352
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7359
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7366
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5414 - accuracy: 0.7353
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7346
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7359
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7367
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7360
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7362
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7362
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7355
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7355
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7363
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7362
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7360
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7365
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7380
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7368
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7358
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7378
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7369
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7362
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7358
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7375
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7370
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7374
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7375
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7369
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7374
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7376
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7377
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7373
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7369
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7374
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7376
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7377
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7373
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7379
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7377
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7381
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7381
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7381
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7382
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7385
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7380
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7385
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7383
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7377
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7374

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5556 - accuracy: 0.7261 - 659ms/epoch - 2ms/step
Loss: 0.5556126236915588, Accuracy: 0.726064145565033

In [20]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(